const autos = [
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":1,
        "name":"RENAULT STEPWAY",        
        "Renaultlink":"https://www.renault.com.co/vehiculos/stepway.html",        
        "version": "zen",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 80.800.000,00" ,
        "note":"Con skis delantero y trasero, ensanchadores laterales, barras de techos funcionales, rines de aluminio de 16” (diamantados en la versión Intens) y una elevada altura al piso.",
        "image":"https://cdn.group.renault.com/ren/co/vehicles/stepway/home/frontal.jpg.ximg.large.webp/4e09c007b7.webp",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":2,
        "name":"RENAULT KWID",        
        "Renaultlink":"https://www.renault.com.co/vehiculos/kwid.html",        
        "version": "zen",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 56.200.000,00" ,
        "note":"El Renault Kwid ha llegado completamente renovado. En el exterior, hay una nueva parrilla delantera, faros delanteros y traseros con tecnología LED, y rines de aluminio diamantados de 14”.",
        "image":"https://cdn.group.renault.com/ren/co/vehicles/kwid/ph2/exterior-kv-kwid-ph2-v2.jpg.ximg.mediumx2.webp/c29669a047.webp",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":3,
        "name":"RENAULT SANDERO",        
        "Renaultlink":"https://www.autocosmos.com.co/catalogo/2023/renault/sandero/life/168639",        
        "version": "Life (2023)",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 64.300.000,00" ,
        "note":"Es uno de los modelos más vendidos en Colombia, el cual incorpora un motor 1,6L 8v 85HP, doble airbag y fijaciones laterales Isofix en la silla trasera. Este modelo incorpora el sistema Media Nav 2.0, que adiciona nuevas funciones de asistencia a la conducción como el ecoscoring y el ecocoaching que brindan parámetros para tener un modo de conducción más eficiente y que permita ahorro en consumo de combustible.",
        "image":"https://cdn.group.renault.com/ren/co/vehicles/sandero/home/sandero-banner-home.jpg.ximg.mediumx2.webp/89ac275c17.webp",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":4,
        "name":"RENAULT LOGAN",        
        "Renaultlink":"https://www.renault.com.co/vehiculos/logan.html",        
        "version": "life",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 67.000.000,00" ,
        "note":"LOGAN reinventa su estilo. La parrilla frontal negra resalta sus faros diurnos con tecnología LED brindando más visibilidad y le dan un mayor estilo.​",
        "image":"https://www.renault.com.co/agg/vn/unique/grade_carrousel_main_1_medium/grade_carrousel_1.png?uri=https%3A%2F%2Fco.co.rplug.renault.com%2Fproduct%2Fmodel%2FL4M%2Flogan%2Fc%2FA-ENS_0MDL2P1SERIELIM1_-TEKNG",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":5,
        "name":"RENAULT DUSTER",        
        "Renaultlink":"https://www.autocosmos.com.co/catalogo/2024/renault/duster-oroch/cargo-4x4/168885",        
        "version": "Cargo 4x4 (2024)",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 96.600.000,00" ,
        "note":"La marca del Rombo ha tenido un gran éxito con la introducción de este modelo en Colombia, gracias a las características competitivas que le han permitido ubicarse como una excelente opción en este segmento de las SUV. Se destaca el sistema Media Nav 2.0, que cuenta ahora con un centro de control, pantalla 100% táctil con funciones de conectividad, multimedia, asistencia al momento de conducir y consejos para reducir el consumo de combustible con funciones como el ecocoaching y ecoscoring.",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/m/RT_V_88b960a46e3f4b4888b7d053ba462e05.jpg",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":6,
        "name":"RENAULT KOLEOS",        
        "Renaultlink":"https://www.renault.com.co/vehiculos/koleos.html",        
        "version": "KOLEOS ZEN CVT 4X2",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 144.700.000,00" ,
        "note":"elegante y atlética, Renault KOLEOS luce un estilo audaz. Afirma su personalidad carismática a través de su diseño refinado y sus curvas deportivas.​",
        "image":"https://cdn.group.renault.com/ren/co/vehicles/koleos/home/koleos-home-oficinas.jpg.ximg.mediumx2.webp/36f76746ab.webp",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":7,
        "name":"RENAULT OROCH",        
        "Renaultlink":"https://www.renault.com.co/vehiculos/oroch.html",        
        "version": "Cargo 4x4",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 80.800.000,00" ,
        "note":"La Renault Oroch acompaña la versatilidad de tus días con el desempeño y el poder 4x4 que necesitas para el trabajo; así como la conectividad y confort para tu vida diaria, con todo el poder y diseño de una pick up.",
        "image":"https://cdn.group.renault.com/ren/co/vehicles/oroch-ph2/oroch-banner-interna.jpg.ximg.mediumx2.webp/7d65e8bc07.webp",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":8,
        "name":"RENAULT ALASKAN",        
        "Renaultlink":"https://www.autocosmos.com.co/catalogo/2023/renault/alaskan/25l-cargo-4x4/168624",        
        "version": "2.5L Cargo 4x4 (2023)",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 200.990.000,00" ,
        "note":"Se trata de la primera Pick-up de gama media de Renault, con capacidad de carga de 1.1 toneladas. Es impulsada por un motor de 2.5 litros turbo diésel y cuenta con opciones de caja manual de seis velocidades o automática de 7 velocidades. El motor genera un torque de 332 lbf y una potencia de 190 HP a 3600 rpm. ",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/xl/RT_V_cbe0b095a7fd4df9a01b7b24181b8472.jpg",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":9,
        "name":"RENAULT TWIZY",        
        "Renaultlink":"https://www.renault.com.co/electricos/twizy.html",        
        "version": "Technic 2023",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Caja con reductor",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Electricidad",
        "Precio sugerido": "$ 57.900.000,00" ,
        "note":"Colombia es el país de América donde se ha vendido el mayor número de unidades de este modelo 100% eléctrico para dos pasajeros. El Twizy es un modelo cero emisiones y cero ruido, que permite una disminución del 80% en el costo del mantenimiento frente a un vehículo de combustión interna. ",
        "image":"https://cdn.group.renault.com/ren/co/vehicles/twizy/home/twizy-interna-home.jpg.ximg.mediumx2.webp/5950c7e713.webp",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":10,
        "name":"RENAULT KANGOO E-TECH",        
        "Renaultlink":"https://www.renault.com.co/electricos/kangoo-e-tech.html",        
        "version": "E-Tech",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Electricidad",
        "Precio sugerido": "$ 136.790.000,00" ,
        "note":"Kangoo E-TECH es la primera minivan eléctrica de producción en masa del mercado con un rango de conducción de 200 km en condiciones reales.",
        "image":"https://cdn.group.renault.com/ren/co/vehicles/kangoo-ze/home/kangoo-ze-interna-home.jpg.ximg.mediumx2.webp/43e8eb1544.webp",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":11,
        "name":"RENAULT KANGOO",        
        "Renaultlink":"https://www.autocosmos.com.co/catalogo/2024/renault/kangoo/16l-carga/168884",        
        "version": "1.6L Carga (2024)",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 83.990.000,00" ,
        "note":"Es un fuerte integrante del segmento de la vans monocasco (FU1), la cual en interior proporciona un ambiente confortable con el espacio suficiente para disfrutar y trabajar, pues tiene una capacidad de carga útil de 799 kg y 2.8 m3 y una práctica accesibilidad. En la carrocería de este modelo se utilizan materiales, elementos de insonorización y estética, desarrollados bajo la alianza del Grupo Renault con el Grupo Daimler.",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/m/RT_V_d939f533995f446c991c6b806d033b2f.jpg",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":12,
        "name":"RENAULT NUEVA MASTER",        
        "Renaultlink":"https://www.renault.com.co/utilitarios/master.html",        
        "version": "zen",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 189.990.000,00" ,
        "note":"Su nuevo diseño 100% renovado por dentro y por fuera reafirma su carácter fuerte y moderno. Nuevo parachoques delantero, nueva parrilla y nuevas luces de circulación diurna con tecnología LED.",
        "image":"https://cdn.group.renault.com/ren/co/vehicles/master/ph2/renault-master-banner-interna.jpg.ximg.mediumx2.webp/ee2d2687f9.webp",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":13,
        "name":"RENAULT TRAFIC",        
        "Renaultlink":"https://www.renault.com.co/vehiculos/stepway.html",        
        "version": "L2H1 Techo Bajo Carga (2023)",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 175.000.000,00" ,
        "note":"Este vehículos comercial fue diseñado para simplificar la vida de los empresarios pyme por la eficacia, capacidad de carga, consumo, desempeño y confort. Cuenta con un propulsor Energy 1.6 dCi Twin Turbo Diésel. Este motor ofrece un doble rendimiento y realiza consumos de menos de 6L/100 km, gracias al Eco-Mode que ayuda a su disminución, regulando el comportamiento del acelerador y del aire acondicionado para reducir el esfuerzo del motor.",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/xl/RT_V_39c8848a6a774bad995c89e00bc09125.jpg",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":14,
        "name":"RENAULT CAPTUR",        
        "Renaultlink":"https://www.autocosmos.com.co/catalogo/2024/renault/captur/16l-zen/168891",        
        "version": "1.6L Zen (2024)",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 112.990.000,00" ,
        "note":"La Captur que llega al mercado colombiano es de procedencia brasilera y utiliza la plataforma de la Duster. Cuenta con un motor 2.0 litros de doble eje de levas(DOHC), cuatro cilindros y 16 válvulas que entrega una potencia máxima de 143 caballos a 5.750 rpm y 146 libras pie de torque a 4.000 rpm. Cuenta con opción de transmisión mecánica de seis velocidades o automática secuencial de cuatro cambios.",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/xl/RT_V_628a1caca69e4e18b516d365022dfe3d.jpg",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":15,
        "name":"RENAULT DUSTER OROCH",        
        "Renaultlink":"https://www.autocosmos.com.co/catalogo/2024/renault/kangoo/16l-carga/168884",        
        "version": "1.6L Carga (2024)",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 102.200.000,00" ,
        "note":"Es una pick-up con carrocería autoportante como las Strada y Saveiro, pero es más grande ofreciendo cabina doble, 4 puertas y espacio para 5 personas, sin embargo es más pequeña y con menos capacidad que las camionetas medianas como las Ranger y Hilux. Cuenta con un platón con capacidad de carga hasta 650 Kg. La Renault Duster Oroch está disponible en dos versiones: Expression y Dynamique 4x2, con una motor 2.0L, 16 válvulas que genera 143 caballos de fuerza. ",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/m/RT_V_88b960a46e3f4b4888b7d053ba462e05.jpg",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":16,
        "name":"RENAULT KANGOO Z.E",        
        "Renaultlink":"https://www.renault.com.co/vehiculos/stepway.html",        
        "version": "zen",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 136.790.000,00" ,
        "note":"El gran argumento del Renault Kangoo Z.E. es que, aparte de su cometido eminentemente utilitario, es que demuestra el compromiso de la marca en la oferta de alternativas de transporte cero emisiones, al ser totalmente eléctrico. Se puede cargar a través de un Wall Box y ello le toma de 6 a 9 horas y una recuperación de 35 km en 1 hora, dependiendo de la potencia de la terminal. Acoger la electricidad en este vehículo de reparto supone disminuir el costo de la movilidad en un 80%, frente a lo que paga un usuario con un vehículo de gasolina.",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/m/RT_V_2c08cafa1eb2418fbeb566618b3a6435.jpg",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":17,
        "name":"RENAULT MASTER",        
        "Renaultlink":"https://www.autocosmos.com.co/catalogo/2023/renault/master/l2h2-carga/168656",        
        "version": "L2H2 Carga (2023)",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 189.990.000,00" ,
        "note":"Esta camioneta tipo van ofrece una amplia versiones de transporte de carga y pasajeros. Permite llevar hasta 17 personas en su versión intermunicipal o hasta 19 personas en su versión escolar-especial. La Renault Master tiene capacidad de 13 m³ de volumen de carga, 6.2 mts de largo y 3.5 toneladas de peso bruto vehicular.",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/m/RT_V_d7e021aee5444776817aeb18391e7d15.jpg",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":18,
        "name":"RENAULT MASTER MINIBUS",        
        "Renaultlink":"https://www.autocosmos.com.co/catalogo/2023/renault/master-minibus/l2h2-pasajeros-12c/168657",        
        "version": "zen",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 222.800.000,00" ,
        "note":"Con skis delantero y trasero, ensanchadores laterales, barras de techos funcionales, rines de aluminio de 16” (diamantados en la versión Intens) y una elevada altura al piso.",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/m/RT_V_766f4d12242a4aaab450c5ced27097ef.jpg",
    },
    {
        "_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":19,
        "name":"RENAULT SANDERO STEPWAY",        
        "Renaultlink":"https://www.renault.com.co/vehiculos/stepway.html",        
        "version": "zen",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 80.800.000,00" ,
        "note":"Con skis delantero y trasero, ensanchadores laterales, barras de techos funcionales, rines de aluminio de 16” (diamantados en la versión Intens) y una elevada altura al piso.",
        "image":"https://cdn.group.renault.com/ren/co/vehicles/stepway/home/stepway-banner-home.jpg.ximg.mediumx2.webp/ca3e438e85.webp",
    },
    {
        //"_id":"5cf1d0dbcd5e98f2540c4d1c",
        "index":20,
        "name":"RENAULT ZOE",        
        "Renaultlink":"https://www.autocosmos.com.co/catalogo/2024/renault/zoe/zen/168883",        
        "version": "zen 2024",
        "motor": "1.6L 16V 111HP MT",
        "Potencia máxima (HP)": "111@5500 rpm",
        "Torque máximo (Nm)": "156@4250 rpm",
        "Caja de velocidades": "Mecánica",
        "Tipo de transmisión": "Delantera",
        "Cilindraje (cm3)": "1598",
        "Número de cilindros": "4",
        "Norma de depolución": "EURO5",
        "Tipo de inyección": "Multipunto secuencial",
        "Tipo de combustible": "Gasolina",
        "Precio sugerido": "$ 169.990.000,00" ,
        "note":"A simple vista es un vehículo compacto, ideal para cuatro o cinco ocupantes, con unas líneas perfectamente demarcadas, que al mirar en detalle permiten descubrir un auto moderno, con curvas tan definidas que le imprimen la elegancia de un vehículo urbano, con un toque de deportividad, gracias a sus detalles especiales.",
        "image":"https://acroadtrip.blob.core.windows.net/catalogo-imagenes/xl/RT_V_a1545d3227384fb9ad303fa4b192277c.webp",
    }
]
